Level UP. Java 2 course. Lesson2 homework
Clairry/level_up_2 pull request #2
Opened 2018-03-12 14:12 UTC by Clairry

2018-03-13 09:31 UTC, Shagbark requested changes

2018-03-13 09:31 UTC, Shagbark commented on src/lesson2/App.java
> +            if (files[i].endsWith(".class")) {
А почему именно ".class"?

2018-03-13 10:11 UTC, Clairry commented on src/lesson2/App.java
> +            if (files[i].endsWith(".class")) {
А вдруг в эту папку еще что-нибудь положат, а нам же только классы нужны...Не надо проверять ".class"?

2018-03-15 06:09 UTC, Shagbark approved these changes

2018-03-15 06:50 UTC, merged